name: my_app
description: Trường Đại học Giao Thông Vận Tải TP. HCM (UTH)

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # API
  dio: ^5.0.2
  http: ^0.13.5

  # HELPER
  equatable: 2.0.5
  logger: ^1.2.2
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  shared_preferences: ^2.0.18
  get_it: 7.2.0
  flutter_dotenv: 5.0.2
  url_launcher: ^6.1.10
  formz: ^0.5.0+1
  flutter_screenutil: ^5.7.0
  uuid: ^3.0.7
  google_fonts: ^4.0.3
  intl: ^0.18.0
  
  # WIDGET
  modal_bottom_sheet: ^3.0.0-pre
  bot_toast: 4.0.3
  shimmer: 2.0.0
  auto_size_text: 3.0.0
  flutter_spinkit: ^5.1.0
  
  # STATE MANAGEMENT
  flutter_bloc: ^8.1.2

  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0

  # OTHER
  change_app_package_name: 1.1.0
  device_preview: ^1.1.0

  # RENDER HTML
  flutter_html: 3.0.0-alpha.3
  flutter_html_table: ^3.0.0-alpha.3

  dart_code_metrics: ^5.7.2
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  auto_route_generator: 5.0.3
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.12.0"
  dart_code_metrics_presets: ^1.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/locale/
